#!/bin/python


MINISCULE_LATIN_ALPHABET = "abgdeθijklmnoprstuwφx"
MAJUSCULE_LATIN_ALPHABET = "ABGDEΘIJKLMNOPRSTUWΦX"
MINUSCULE_LATIN_SHORT_VOWELS = "aeiou"
MINISCULE_LATIN_LONG_VOWELS = "āēīōū"
MAJUSCULE_LATIN_SHORT_VOWELS = "AEIOU"
MAJUSCULE_LATIN_LONG_VOWELS = "ĀĒĪŌŪ"
MISCELLANEOUS = " -"
MINISCULE_CYRILLIC_ALPHABET = "абгдеѳийклмнопрстуўфх"
MAJUSCULE_CYRILLIC_ALPHABET = "АБГДЕѲИЙКЛМНОПРСТУЎФХ"
MINISCULE_CYRILLIC_SHORT_VOWELS = "аеиоу"
MAJUSCULE_CYRILLIC_SHORT_VOWELS = "АЕИОУ"
MACRON = "\u0304"
COLON = ":"
